import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    scanner: 'Scanner',
    sessions: 'Sessions',
    participants: 'Participants',
    events: 'Events',
    admin: 'Admin',
    sign_out: 'Sign out',
    
    // TopBar
    search_participants: 'Search participants...',
    command_dashboard: 'Command Dashboard',
    checkin_scanner: 'Check-in Scanner',
    session_attendance_engine: 'Session Attendance Engine',
    participant_registry: 'Participant Registry',
    event_management: 'Event Management',
    administration: 'Administration',
    
    // Common
    name: 'Name',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    welcome_back: 'Welcome back',
    sign_in_to_account: 'Sign in to your administrator account',
    digital_ticket: 'Get Digital Ticket',
    demo_accounts: 'Demo Accounts',
    loading: 'Loading...',
    login_failed: 'Login failed',
    count: 'Count',
    date_time: 'Date / Time',
    venue_room: 'Venue / Room',
    success: 'Success',
    error: 'Error',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    actions: 'Actions',
    search: 'Search',
    
    // Roles
    staff: 'Staff',
    manager: 'Manager',
    admin_role: 'Admin',
    speaker: 'Speaker',
    chairperson: 'Chairperson',
    vip: 'VIP',
    participant: 'Participant',
    all_roles: 'All Roles',
    all_events: 'All Events',
    
    // Dashboard Extra
    total_events: 'Total Events',
    live_checkins: 'Live Check-ins',
    total_registered: 'Total Registered',
    event_hierarchy: 'Event Hierarchy',
    event_hierarchy_desc: 'Global Events → Sub-Events → Sessions → Participants',
    recent_checkins: 'Recent Check-ins',
    no_events_found: 'No events found. Create your first event to get started.',
    checkin_rate_desc: 'Overall Check-in Rate',
    live: 'Live',
    sessions_today: 'Sessions Today',
    
    // Events Extra
    no_venue: 'No venue',
    upcoming_status: 'Upcoming',
    active_status_badge: 'Active',
    completed_status: 'Completed',
    cancelled_status: 'Cancelled',
    enterprise: 'Enterprise',
    event_arrival: 'Event Arrival',
    venue_checkin: 'Venue Check-in',
    speaker_verify: 'Speaker Verify',
    checkin_success: 'Check-in Successful',
    already_checked_in: 'Already Checked In',
    checkin_failed: 'Check-in Failed',
    continue_scanning: 'Continue Scanning',
    manual_entry: 'Manual Entry',
    camera_qr: 'Camera QR',
    processing: 'Processing...',
    active: 'Active',
    manual_entry_desc: 'Enter QR code or ticket number — Press Enter',
    process_checkin: 'Process Check-in',
    scan_frame_desc: 'Position code within the frame',
    validation_history: 'Validation History',
    scans: 'scans',
    no_scans: 'No scans yet',
    stage: 'Stage',
    allowed: 'Allowed',
    restricted: 'Restricted',
    rbac_title: 'RBAC Role Guide',
    staff_management: 'Staff Management',
    user_activated: 'User session activated',
    user_deactivated: 'User session deactivated',
    reset_password: 'Reset Password',
    update_password: 'Update Password',
    delete_user: 'Delete User',
    delete_confirm: 'Are you sure you want to delete this user?',
    joined: 'Joined',
    password_min_length: 'Password must be 6+ characters',
    
    // Modals
    edit_event: 'Edit Event',
    new_event: 'New Event',
    event_description: 'Event Description',
    edit_sub_event: 'Edit Sub-Event',
    new_sub_event: 'New Sub-Event',
    edit_session: 'Edit Session',
    new_session: 'New Session',
    session_title: 'Session Title',
    speaker_name: 'Speaker Name',
    room_location: 'Room / Location',
    start_time: 'Start Time',
    end_time: 'End Time',
    capacity: 'Capacity',
    sub_event: 'Sub-Event',
    session: 'Session',
    no_sub_events: 'No sub-events found.',
    no_sessions: 'No sessions assigned',
    
    // Public Registration
    participant_registration: 'Participant Registration',
    fill_details: 'Fill in these details to get your digital ticket',
    organization: 'Organization',
    register: 'Register',
    registration_closed: 'Registration Closed',
    back_to_login: 'Back to Login',
    select_event: 'Select Event',
    registration_complete: 'Registration Complete!',
    digital_ticket_ready: 'Your digital ticket is ready',
    screenshot_qr: 'Please take a screenshot of this QR code and present it to staff at the reception.',
    register_another: 'Register another person',
    no_active_events: 'No active events are currently accepting registrations.',
    complete_registration: 'Complete Registration',
    showing: 'Showing',
    of: 'of',
    
    // Status
    active_status: 'Active',
    inactive_status: 'Inactive',
    
    // Permissions
    perm_all: 'All features',
    perm_users: 'User management',
    perm_delete_events: 'Delete events',
    perm_force_exit: 'Force exit sessions',
    perm_roles: 'Role assignment',
    perm_config: 'System config',
    perm_create_events: 'Create/edit events',
    perm_add_participants: 'Add participants',
    perm_import_export: 'Import/export CSV',
    perm_manage_sessions: 'Manage sessions',
    perm_reports: 'View all reports',
    perm_view_dash: 'View dashboard',
    perm_run_scanner: 'Run scanner',
    perm_view_participants: 'View participants',
    perm_session_checkins: 'Session check-ins',
    restricted_admin_panel: 'Admin panel',
    
    // Login Branding
    scoring_platform: 'EventHQ Platform',
    manage_contests: 'Seamless reception for your events',
    platform_description: 'Streamline participant check-ins and session attendance with real-time tracking.',
    feature_realtime: 'Real-time check-in syncing',
    feature_multi_judge: 'Multi-device sync',
    feature_custom_templates: 'Custom ticket printing',
    feature_instant_results: 'Instant attendance reports',
    dont_have_qr: 'Attending without a ticket?',
    all_roles: 'All Roles',
    ticket_no: 'Ticket No.',
    add_participant: 'Add Participant',
    import_csv: 'Import CSV',
    no_participants: 'No participants found',
    failed_load_sessions: 'Failed to load sessions',
    failed_load_details: 'Failed to load session details',
    checkout_success: 'Checked out successfully',
    checkout_failed: 'Checkout failed',
    no_sessions_found: 'No sessions found',
    attending: 'attending',
    select_session_monitor: 'Select a session to monitor',
    no_room: 'No room',
    no_speaker: 'No speaker',
    live_attendees: 'Live Attendees',
    no_active_attendees: 'No active attendees in this session',
    entry_time: 'Entry Time',
    duration: 'Duration',
    guard: 'Guard',
    cleared: 'Cleared',
    check_out: 'Check Out',
    guard_active_title: '3-Minute Guard Active',
    guard_active_desc: 'Minimum attendance period not completed.',
    remaining: 'remaining',
    guard_long_desc: 'This participant checked in less than 3 minutes ago. Administrative override is available for emergencies only.',
    dismiss: 'Dismiss',
    force_exit: 'Force Exit',
    upcoming: 'Upcoming',
    completed: 'Completed',
    minutes_short: 'm',
    seconds_short: 's',
    session_updated: 'Session updated',
    session_created: 'Session created',
    failed_save_session: 'Failed to save session',
    create_session: 'Create Session',
    create_event: 'Create Event',
    event_name: 'Event Name',
    capacity_short: 'Cap',
    stage1_desc: 'Validates participant registration. Marks event arrival timestamp.',
    stage2_desc: 'Grants venue access. Requires Stage 1 to be completed first.',
    stage3_desc: 'Verifies speakers, chairpersons, and VIPs. Requires Stage 1.',
    you: '(you)',
    set_new_pw_for: 'Set a new password for',
    pw_placeholder: 'New password (min 6 chars)',
    admin_role: 'Admin',
    manager_role: 'Manager',
    staff_role: 'Staff',
    email_header: 'Email Address',
    qr_code_label: 'QR Code',
    digital_ticket: 'Digital Ticket',
    page_label: 'Page',
    importing: 'Importing...',
    export_csv: 'Export CSV',
    of: 'of',
    // Event/Session form labels
    start_date: 'Start Date',
    end_date: 'End Date',
    venue: 'Venue',
    speakers: 'Speakers',
    chairs: 'Chairs / Chairpersons',
    phone: 'Phone',
    unlimited: 'Unlimited',
    status: 'Status',
    upcoming: 'Upcoming',
    cancelled: 'Cancelled',
    edit_participant: 'Edit Participant',
    click_name_to_expand: 'Click name to reveal email & QR',
  },
  ja: {
    // Navigation
    dashboard: 'ダッシュボード',
    scanner: 'スキャナー',
    sessions: 'セッション',
    participants: '参加者',
    events: 'イベント',
    admin: '管理者',
    sign_out: 'ログアウト',
    
    // TopBar
    search_participants: '参加者を検索...',
    command_dashboard: 'コマンドダッシュボード',
    checkin_scanner: 'チェックインスキャナー',
    session_attendance_engine: 'セッション出席エンジン',
    participant_registry: '参加者登録簿',
    event_management: 'イベント管理',
    administration: '管理設定',
    
    // Common
    name: '名前',
    email: 'メールアドレス',
    password: 'パスワード',
    login: 'ログイン',
    welcome_back: 'おかえりなさい',
    sign_in_to_account: '管理者アカウントでサインイン',
    digital_ticket: 'デジタルチケットを取得',
    demo_accounts: 'デモアカウント',
    loading: '読み込み中...',
    login_failed: 'ログインに失敗しました',
    count: '数',
    date_time: '日付 / 時間',
    venue_room: '会場 / 部屋',
    success: '成功',
    error: 'エラー',
    save: '保存',
    cancel: 'キャンセル',
    edit: '編集',
    delete: '削除',
    actions: '操作',
    search: '検索',
    
    // Roles
    staff: 'スタッフ',
    manager: 'マネージャー',
    admin_role: '管理者',
    speaker: '登壇者',
    chairperson: '座長',
    vip: 'VIP',
    participant: '参加者',
    all_roles: 'すべての役割',
    all_events: 'すべてのイベント',
    
    // Dashboard Extra
    total_events: '総イベント数',
    live_checkins: 'ライブチェックイン',
    total_registered: '全登録者数',
    event_hierarchy: 'イベント階層',
    event_hierarchy_desc: 'グローバルイベント → サブイベント → セッション → 参加者',
    recent_checkins: '最近のチェックイン',
    no_events_found: 'イベントが見つかりません。最初のイベントを作成して開始してください。',
    checkin_rate_desc: '全体のチェックイン率',
    live: 'ライブ',
    sessions_today: '本日のセッション',
    
    // Events Extra
    no_venue: '会場未設定',
    upcoming_status: '開催予定',
    active_status_badge: '実施中',
    completed_status: '完了',
    cancelled_status: 'キャンセル',
    enterprise: 'エンタープライズ',
    event_arrival: 'イベント受付',
    venue_checkin: '会場受付',
    speaker_verify: 'スピーカー確認',
    checkin_success: 'チェックイン完了',
    already_checked_in: 'チェックイン済み',
    checkin_failed: 'チェックイン失敗',
    continue_scanning: 'スキャンを続ける',
    manual_entry: '手動入力',
    camera_qr: 'カメラQR',
    processing: '処理中...',
    active: 'アクティブ',
    manual_entry_desc: 'QRコードまたはチケット番号を入力してください',
    process_checkin: 'チェックイン',
    scan_frame_desc: 'フレーム内にコードを合わせてください',
    validation_history: '認証履歴',
    scans: 'スキャン',
    no_scans: '履歴なし',
    stage: 'ステージ',
    allowed: '許可',
    restricted: '制限済み',
    rbac_title: '役割別アクセスガイド',
    staff_management: 'スタッフ管理',
    user_activated: 'ユーザーを有効にしました',
    user_deactivated: 'ユーザーを無効にしました',
    reset_password: 'パスワードをリセット',
    update_password: 'パスワードを更新',
    delete_user: 'ユーザーを削除',
    delete_confirm: 'このユーザーを削除してもよろしいですか？',
    joined: '登録日',
    password_min_length: 'パスワードは6文字以上で入力してください',
    
    // Modals
    edit_event: 'イベントを編集',
    new_event: '新規イベント',
    event_description: 'イベントの説明',
    edit_sub_event: 'サブイベントを編集',
    new_sub_event: '新規サブイベント',
    edit_session: 'セッションを編集',
    new_session: '新規セッション',
    session_title: 'セッション名',
    speaker_name: '登壇者名',
    room_location: '部屋 / 場所',
    start_time: '開始時間',
    end_time: '終了時間',
    capacity: '定員',
    sub_event: 'サブイベント',
    session: 'セッション',
    no_sub_events: 'サブイベントがありません。',
    no_sessions: 'セッションが割り当てられていません',
    
    // Public Registration
    participant_registration: '参加者登録',
    fill_details: '以下の詳細を入力してデジタルチケットを取得してください',
    organization: '組織・団体名',
    register: '登録する',
    registration_closed: '登録期間外',
    back_to_login: 'ログインに戻る',
    select_event: 'イベントを選択',
    registration_complete: '登録完了！',
    digital_ticket_ready: 'デジタルチケットの準備ができました',
    screenshot_qr: 'このQRコードのスクリーンショットを撮り、受付でスタッフに提示してください。',
    register_another: '別の人を登録する',
    no_active_events: '現在、登録を受け付けているアクティブなイベントはありません。',
    complete_registration: '登録を完了する',
    showing: '表示中:',
    of: '/',
    
    // Status
    active_status: '有効',
    inactive_status: '無効',
    
    // Permissions
    perm_all: 'すべての機能',
    perm_users: 'ユーザー管理',
    perm_delete_events: 'イベントの削除',
    perm_force_exit: 'セッションの強制終了',
    perm_roles: '役割の割り当て',
    perm_config: 'システム設定',
    perm_create_events: 'イベントの作成・編集',
    perm_add_participants: '参加者の追加',
    perm_import_export: 'CSVインポート・エクスポート',
    perm_manage_sessions: 'セッション管理',
    perm_reports: 'すべてのレポートを表示',
    perm_view_dash: 'ダッシュボードを表示',
    perm_run_scanner: 'スキャナーを実行',
    perm_view_participants: '参加者を表示',
    perm_session_checkins: 'セッションチェックイン',
    restricted_admin_panel: '管理パネル',
    
    // Login Branding
    scoring_platform: 'EventHQ プラットフォーム',
    manage_contests: 'イベント受付をスムーズに',
    platform_description: '参加者のチェックインとセッションの出席状況をリアルタイムで追跡・管理します。',
    feature_realtime: 'リアルタイムのチェックイン同期',
    feature_multi_judge: 'マルチデバイス同期',
    feature_custom_templates: 'カスタムチケット印刷',
    feature_instant_results: '即時の出席レポート',
    dont_have_qr: 'チケットをお持ちでないですか？',
    all_roles: 'すべての役割',
    ticket_no: 'チケット番号',
    add_participant: '参加者を追加',
    import_csv: 'CSVインポート',
    no_participants: '参加者が見つかりません',
    failed_load_sessions: 'セッションの読み込みに失敗しました',
    failed_load_details: 'セッション詳細の読み込みに失敗しました',
    checkout_success: 'チェックアウトが完了しました',
    checkout_failed: 'チェックアウトに失敗しました',
    no_sessions_found: 'セッションが見つかりません',
    attending: '名が出席中',
    select_session_monitor: '監視するセッションを選択してください',
    no_room: '部屋未設定',
    no_speaker: '登壇者未設定',
    live_attendees: '現在の出席者',
    no_active_attendees: 'このセッションにアクティブな出席者はいません',
    entry_time: '入場時間',
    duration: '滞在時間',
    guard: 'ガード',
    cleared: '解除',
    check_out: 'チェックアウト',
    guard_active_title: '3分間ガード発動中',
    guard_active_desc: '最短出席時間に達していません。',
    remaining: '残り',
    guard_long_desc: 'この参加者はチェックインから3分経過していません。管理者による上書きは緊急時のみ使用してください。',
    dismiss: '閉じる',
    force_exit: '強制退場',
    upcoming: '開催予定',
    completed: '完了',
    minutes_short: '分',
    seconds_short: '秒',
    session_updated: 'セッションを更新しました',
    session_created: 'セッションを作成しました',
    failed_save_session: 'セッションの保存に失敗しました',
    create_session: 'セッションを作成',
    create_event: 'イベントを作成',
    event_name: 'イベント名',
    capacity_short: '定員',
    stage1_desc: '参加者登録を検証し、イベント到着時間を記録します。',
    stage2_desc: '会場への入場を許可します。事前にステージ1を完了している必要があります。',
    stage3_desc: '登壇者、座長、VIPを検証します。事前にステージ1を完了している必要があります。',
    you: '(あなた)',
    set_new_pw_for: '以下のユーザーの新しいパスワードを設定:',
    pw_placeholder: '新しいパスワード（6文字以上）',
    admin_role: '管理者',
    manager_role: 'マネージャー',
    staff_role: 'スタッフ',
    email_header: 'メールアドレス',
    qr_code_label: 'QRコード',
    digital_ticket: 'デジタルチケット',
    page_label: 'ページ',
    importing: 'インポート中...',
    export_csv: 'CSVエクスポート',
    of: 'の',
    // Event/Session form labels
    start_date: '開始日',
    end_date: '終了日',
    venue: '会場',
    speakers: '登壇者',
    chairs: '座長 / 司会者',
    phone: '電話番号',
    unlimited: '無制限',
    status: 'ステータス',
    upcoming: '開催予定',
    cancelled: 'キャンセル',
    edit_participant: '参加者を編集',
    click_name_to_expand: '名前をクリックしてメール・QRを表示',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('eventhq_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('eventhq_lang', lang);
    document.documentElement.setAttribute('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
